### PR TITLE
Remove all references to Mike Lieberman's personal github

### LINKED ISSUE #7: Remove all references to Mike Lieberman's personal github
All images should be part of this org. Where applicable all code that will be specifically part of the SSF should be under this repo or at least under this org.

### PR DESCRIPTION
**Pull request by lmilbaum**
fix #7

### CODE REVIEW

**Comment by lmilbaum** [comment]
@mlieberman85 I am not sure this is the proper fix. Would appreciate your feedback.

**Comment by sudo-bmitch** [comment]
For demos, we may want to use a local registry or `ttl.sh` rather than pushing directly to `ghcr.io`.

**Comment by lmilbaum** [comment]
> For demos, we may want to use a local registry or `ttl.sh` rather than pushing directly to `ghcr.io`.

Makes sense. Do you know how to operate the demo or maybe referring me to a README? That would help me understand how to implement the change and to test it.

**Comment by sudo-bmitch** [comment]
> Makes sense. Do you know how to operate the demo or maybe referring me to a README? That would help me understand how to implement the change and to validate it.

I am not as familiar with these, I think they are from @mlieberman85 's presentations. We've mostly been working off the makefile and examples.

**Comment by mlieberman85** [comment]
For a little bit of background. This all started based on a demo I gave at Kubecon and a few other places. This then ended up turning into SSF itself. We probably can remove some of this stuff and look at developing new demos.

**Comment by lmilbaum** [comment]
What is blocking us from reviewing the PR?

**Pull request closed without merging**
