### PR TITLE
Simplify sample-pipeline

### PR DESCRIPTION
**Pull request by bradbeck**
Simplify sample-pipeline by reusing existing tasks from Tekton Catalog:
* `git-clone`
* `kaniko`

### CODE REVIEW

**Review by sudo-bmitch — APPROVED** [review]
LGTM. Was there any need to have these in cue before, or was that just part of getting everything in cue and sorting it out later?

**Comment by bradbeck** [comment]
> LGTM. Was there any need to have these in cue before, or was that just part of getting everything in cue and sorting it out later?

The original YAML contained these custom task definitions which originally were intended to be signed by tapestry.

This change further moves away from the tapestry task signing approach and makes this pipeline more consistent with the other examples.

**Review by joshualucas84 — APPROVED** [review]
LGTM!

**Review by sudo-bmitch — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Pull request merged**
